import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-renderer%lib{crails-renderer}
import intf_libs += libcrails-random%lib{crails-random}
import intf_libs += libcrails-http-client%lib{crails-http-client}

lib{crails-sync}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-sync}:
{
  cxx.export.poptions = "-I$out_root/libcrails-sync/" "-I$src_root/libcrails-sync/"
  cxx.export.libs = $intf_libs
}

liba{crails-sync}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-sync}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-sync}: bin.lib.version = "-$version.project_id"
else
  lib{crails-sync}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-sync/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
